/* eslint-disable n8n-nodes-base/node-param-operation-option-action-miscased */
import { INodeType, INodeTypeDescription, NodeConnectionType } from 'n8n-workflow';
import {
	deleteCollectionOperation,
	retrievePointOperation,
	retrievePointFields,
	deleteCollectionFields,
	listCollectionsOperation,
	getCollectionOperation,
	getCollectionFields,
	listCollectionsFields,
	collectionExistsOperation,
	collectionExistsFields,
	createCollectionOperation,
	createCollectionFields,
	queryPointsOperation,
	queryPointsFields,
	queryBatchPointsOperation,
	queryBatchPointsFields,
	queryPointsGroupsOperation,
	queryPointsGroupsFields,
	matrixPairsOperation,
	matrixPairsFields,
	matrixOffsetsOperation,
	matrixOffsetsFields,
	retrievePointsOperation,
	retrievePointsFields,
	upsertPointsOperation,
	upsertPointsFields,
	deletePointsOperation,
	deletePointsFields,
	updateVectorsOperation,
	updateVectorsFields,
	deleteVectorsOperation,
	deleteVectorsFields,
	setPayloadOperation,
	setPayloadFields,
	overwritePayloadOperation,
	overwritePayloadFields,
	deletePayloadOperation,
	deletePayloadFields,
	clearPayloadOperation,
	clearPayloadFields,
	batchUpdatePointsOperation,
	batchUpdatePointsFields,
	scrollPointsOperation,
	scrollPointsFields,
	countPointsOperation,
	countPointsFields,
	payloadFacetsOperation,
	payloadFacetsFields,
	createPayloadIndexOperation,
	createPayloadIndexFields,
	deletePayloadIndexOperation,
	deletePayloadIndexFields,
} from './descriptions';

const inputs = [NodeConnectionType.Main];
const outputs = [NodeConnectionType.Main];

export class Qdrant implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Qdrant',
		name: 'qdrant',
		icon: 'file:qdrant.svg',
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"]}}',
		description: 'Node to interface with the Qdrant Vector Database',
		defaults: {
			name: 'Qdrant',
		},
		usableAsTool: true,
		inputs,
		outputs,
		credentials: [
			{
				name: 'qdrantApi',
				required: true,
			},
		],
		requestDefaults: {
			baseURL: '={{$credentials.url}}',
			headers: {
				'Content-Type': 'application/json',
			},
		},
		properties: [
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				options: [
					listCollectionsOperation,
					deleteCollectionOperation,
					getCollectionOperation,
					collectionExistsOperation,
					createCollectionOperation,
					retrievePointOperation,
					retrievePointsOperation,
					upsertPointsOperation,
					deletePointsOperation,
					updateVectorsOperation,
					deleteVectorsOperation,
					setPayloadOperation,
					overwritePayloadOperation,
					deletePayloadOperation,
					clearPayloadOperation,
					batchUpdatePointsOperation,
					scrollPointsOperation,
					countPointsOperation,
					queryPointsOperation,
					queryBatchPointsOperation,
					queryPointsGroupsOperation,
					matrixPairsOperation,
					matrixOffsetsOperation,
					payloadFacetsOperation,
					createPayloadIndexOperation,
					deletePayloadIndexOperation,
				],
				default: '',
			},
			...listCollectionsFields,
			...deleteCollectionFields,
			...retrievePointFields,
			...getCollectionFields,
			...collectionExistsFields,
			...createCollectionFields,
			...queryPointsFields,
			...queryBatchPointsFields,
			...queryPointsGroupsFields,
			...matrixPairsFields,
			...matrixOffsetsFields,
			...retrievePointsFields,
			...upsertPointsFields,
			...deletePointsFields,
			...updateVectorsFields,
			...deleteVectorsFields,
			...setPayloadFields,
			...overwritePayloadFields,
			...deletePayloadFields,
			...clearPayloadFields,
			...batchUpdatePointsFields,
			...scrollPointsFields,
			...countPointsFields,
			...payloadFacetsFields,
			...createPayloadIndexFields,
			...deletePayloadIndexFields,
		],
	};
}
