name: Publish NPM Package
on:
  workflow_dispatch:

jobs:
  npm-release:
    name: NPM Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Clean Install
        run: |
          npm ci
      - name: NPM Publish
        run: |
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}